name: Clone documentation from code repo

on:
  schedule:
    - cron: "0 0 * * *"
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          repository: eclipse-wattadvisor/wattadvisor
          path: code
          
      - name: Checkout website repository
        uses: actions/checkout@v4
        with:
          repository: eclipse-wattadvisor/website
          path: website

      - name: Copy Documentation to Repository B
        run: cp -r code/docs/build/html/* website

      - name: Commit and Push Changes
        run: |
          cd website
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Automated commit." || exit 0
          git push
